### ISSUE TITLE
Not installing on Termux 

### ISSUE THREAD

**Issue by srt54558** [htr-tech/track-ip#11]
![Screenshot_20220321_140044.jpg](https://user-images.githubusercontent.com/90862487/159266084-eedca64b-9b7b-4c47-8cd7-927bd977635d.jpg)

I ran the code from the installation guide. Even Google could not help, so hopefully it can be fixed by htr-tech... If not it's not working on termux apparently.
On Kali Linux it works fine tho.

**Comment by htr-tech** [comment]
try `git clone https://github.com/htr-tech/track-ip.git` this will fix the issue
