### ISSUE TITLE
How to open from main menu

### ISSUE THREAD

**Issue by lord-Hasli** [htr-tech/track-ip#9]
Command to open from termux main menu

**Comment by htr-tech** [comment]
If you have installed this on home dir then try

```bash track-ip/trackip```

**Comment by lord-Hasli** [comment]
Other tool

**Comment by lord-Hasli** [comment]
How can i open

**Comment by htr-tech** [comment]
what do you mean by other tool ?

**Comment by lord-Hasli** [comment]
For ip it is not working![Screenshot_20220113_210630.jpg](https://user-images.githubusercontent.com/97538980/149360565-db7fdd6b-d8b5-4b5d-9693-5529d6017266.jpg)

**Comment by htr-tech** [comment]
you have to go to the directory first 
`cd track-ip`
then type `bash trackip`

**Comment by ghost** [comment]
As the owner wrote in the README, here are the instuctions on how to open and run this script:
- `apt update`
- `apt install git curl -y`
- `git clone git://github.com/htr-tech/track-ip.git`
- `cd track-ip`
- `bash trackip`

**Comment by Jkdaksh** [comment]
It's fake it doesn't give live location this source give us face location

**Comment by mohammadhossein-dev** [comment]
It doesn't work really, it gives the wrong location.

**Comment by TheJinn2614** [comment]
> It's fake it doesn't give live location this source give us face location
> 

You dont seem to know much about IPs nor networking to begin with xD
